// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWrAV6JED-FjegwWlx2dvn4oBK0J3Amko',
    appId: '1:409147253126:web:3021580864a6ffef3bcc07',
    messagingSenderId: '409147253126',
    projectId: 'skopjeapp-56f6c',
    authDomain: 'skopjeapp-56f6c.firebaseapp.com',
    storageBucket: 'skopjeapp-56f6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJ-LAOoNCEN9zDeHm8S1OqF8n2SY3ZGw',
    appId: '1:409147253126:android:3a9cc1744d8968bd3bcc07',
    messagingSenderId: '409147253126',
    projectId: 'skopjeapp-56f6c',
    storageBucket: 'skopjeapp-56f6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvK2HOS6qddWjCyJhdXJEpvv_l0ns822c',
    appId: '1:409147253126:ios:0639c1dd9f4f9ad73bcc07',
    messagingSenderId: '409147253126',
    projectId: 'skopjeapp-56f6c',
    storageBucket: 'skopjeapp-56f6c.appspot.com',
    iosBundleId: 'com.example.skopjeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvK2HOS6qddWjCyJhdXJEpvv_l0ns822c',
    appId: '1:409147253126:ios:23df3d184ef3d6b93bcc07',
    messagingSenderId: '409147253126',
    projectId: 'skopjeapp-56f6c',
    storageBucket: 'skopjeapp-56f6c.appspot.com',
    iosBundleId: 'com.example.skopjeapp.RunnerTests',
  );
}
